name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    - cron: '0 9 * * *'

jobs:
  integration: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - core20
          - core22
          - core24
    steps:
    - uses: actions/checkout@v4
      with:
        path: './action-build'
    - run: |
        cp -a action-build/test-projects/${{ matrix.project }}/* .
    - uses: ./action-build
      id: snapcraft
    - uses: actions/upload-artifact@v4
      with:
        name: 'snap-${{ matrix.project }}'
        path: ${{ steps.snapcraft.outputs.snap}}
        compression-level: 0
        retention-days: 7

  collect-artifacts:
    needs:
      - integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/upload-artifact/merge@v4
      with:
        name: snap
        pattern: snap-*
        delete-merged: true
        retention-days: 7

  check-runner: # make sure the action works on each VM image
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: './action-build'
    - run: |
        cp -a action-build/test-projects/core24/* .
    - uses: ./action-build
